# Changes here will be overwritten by Copier
AnswerStrategy: recommended
Authors: Sofiane <sofiane.tanji@uclouvain.be>
CodeOfConductContact: sofiane.tanji@uclouvain.be
ConfigIndentation: 2
JuliaIndentation: 4
JuliaMinVersion: '1.10'
License: MIT
LicenseCopyrightHolders: Sofiane
MarkdownIndentation: 2
PackageName: Dyle
PackageOwner: SofianeTanji
PackageUUID: e00da184-d7e2-53e1-b9b4-77df80479b38
_commit: v0.15.0
_src_path: https://github.com/JuliaBesties/BestieTemplate.jl
